public class BR_EventDetailController {
	/*@AuraEnabled
    //just getting one event
    public static Map<String, Object> getEventMap(Id recordId){
        return CalendarController.getEventMap(recordId);
    }
    
    @AuraEnabled
    public static String getEventRelationship(String eventId) {
        return CalendarController.getEventRelationship(eventId);
    }
    
    @AuraEnabled
    public static String bookAnEvent(String eventId) {
        return CalendarController.bookAnEvent(eventId);
    }
    
    @AuraEnabled
    public static Map<String, String> bookARecurrence(String eventId) {
        return CalendarController.bookARecurrence(eventId);
    }
    
    @AuraEnabled
    public static String deleteAnEvent(String eventId, String reason) {
        return CalendarController.deleteAnEvent(eventId, reason);
    }
    
    @AuraEnabled
    public static Map<String, String> deleteARecurrence(String eventId, String reason) {
        return CalendarController.deleteARecurrence(eventId, reason);
    }
    
    //updateEvent here is for changing date time AND other attributes available in the edit form
    //use the 'Edit Form Change' changeType
    @AuraEnabled
    public static List<Map<String, String>> updateEvent(String updateJSON, String action) {
        return CalendarController.updateEventEditForm(updateJSON, action);
    }*/
}