@isTest
public class ExtractItemTriggerHandlerTest
{
    @IsTest
    static void test1()
    {
        //TestLoadData data = new TestLoadData();
        //data.LoadRecords();
        //data.LoadServiceAgreements();
        //data.LoadServiceDelivered();
        //Test.startTest();
        //data.loadExtract();

        //List<enrtcr__Extract_Item__c> exiList = new List<enrtcr__Extract_Item__c>([SELECT Id, enrtcr__Claim_Status__c FROM enrtcr__Extract_Item__c]);
        //for(enrtcr__Extract_Item__c exi : exiList)
        //{
         //   exi.enrtcr__Claim_Status__c = 'Paid';
        //}
        //UPDATE exiList;

        //DELETE exiList[0];
    }
}