/**
 * Created by Enrite Solutions on 24/07/2019.
 */

public class XeroAddress {

    public String AddressType {get; set;}
    public String AddressLine1 {get; set;}
    public String AddressLine2 {get; set;}
    public String AddressLine3 {get; set;}
    public String AddressLine4 {get; set;}
    public String City {get; set;}
    public String Region {get; set;}
    public String PostalCode {get; set;}
    public String Country {get; set;}
    public String AttentionTo {get; set;}

}