/**
 * Created by Enrite Solutions on 4/01/2021.
 */

public with sharing class XeroConstants {

    public static final String XERO_PHONE_TYPE_MOBILE = 'MOBILE';
    public static final String XERO_ADDRESS_TYPE_OTHER = 'POBOX';
    public static final String XERO_ADDRESS_TYPE_MAILING = 'STREET';
    public static final String POST_METHOD = 'POST';
    public static final String XERO_TYPE_CONTACTS = 'Contacts';
    public static final String XERO_TYPE_INVOICES = 'Invoices';
    public static final String XERO_TYPE_INVOICES_SUMMARISE_ERRORS = 'Invoices?SummarizeErrors=false';
    public static final String XERO_INVOICE_TYPE_ACCREC = 'ACCREC';
    public static final String INVOICE_LINE_ITEM_TYPE = 'EXEMPTOUTPUT';

}